adjective1 = input("Enter an adjective (description):")
noun1 = input("Enter a noun (person, place, thing): ")
adjective2 = input("Enter an adjective (description):")
verb1 = input("Enter a verb ending with 'ing'")
adjective3 = input("Enter an adjective (description): ")

print("today i went to a", adjective1, "zoo")
print("In an exhibit, I saw a ", noun1)
print("the", noun1, " was", adjective2 and verb1)
print("i was", adjective3)